<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.1.1</version>
    <relativePath />
  </parent>

  <groupId>tech.axiominfo</groupId>
  <artifactId>foundry</artifactId>
  <version>${revision}</version>

  <name>Foundry</name>

  <description></description>

  <properties>
    <revision>0.0.1-SNAPSHOT</revision>

    <java.version>25</java.version>
    <npm.version>11.11.0</npm.version>
    <node.version>v24.21.0</node.version>

    <maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
    <maven-dependency-plugin.version>3.11.0</maven-dependency-plugin.version>
    <asciidoctor-maven-plugin.version>3.2.0</asciidoctor-maven-plugin.version>
  </properties>

  <modules>
    <module>agent</module>
    <module>ui</module>
    <module>service</module>
  </modules>

  <packaging>pom</packaging>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>${maven-checkstyle-plugin.version}</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
        <configuration>
          <skip>true</skip>
          <buildArgs>
            <arg>-H:-CheckToolchain</arg>
            <arg>-H:+ReportExceptionStackTraces</arg>
            <arg>--verbose</arg>
            <arg>-J-Xmx8g</arg>
          </buildArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
