logging:
  file:
    name: logs/service.log
  level:
    org:
      springframework:
        security: INFO
        web: DEBUG
    tech:
      axiominfo: INFO

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/actuator
      exposure:
        include: flyway,health,info
  endpoint:
    flyway:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env.enabled: true
    java.enabled: true
    os.enabled: true

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  error:
    whitelabel:
      enabled: false
  max-http-request-header-size: 16384
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

spring:
  data:
    rest:
      base-path: /api

  datasource:
    # h2
    driver-class-name: org.h2.Driver
    # postgres
    # driver-class-name: org.postgresql.Driver

    # h2 in memory
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # h2 file
    # url: jdbc:h2:./service.h2.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # postgres
    # url: jdbc:postgresql://localhost:5432/service

    username: service
    password: service

  jpa:
    # postgres
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: true
    show-sql: true

  devtools:
    add-properties: true
    livereload:
      enabled: true
      port: 35729
    remote:
      restart:
        enabled: false
    restart:
      additional-paths: ../ui/dist

  flyway:
    enabled: true
    encoding: UTF-8

  h2:
    console:
      enabled: false
      path: /h2-console

  main:
    allow-bean-definition-overriding: false
    allow-circular-references: false
    banner-mode: console
    log-startup-info: true

  mvc.servlet.path: /

  profiles:
    default: default

  sql:
    init:
      platform: all

  thymeleaf:
    prefix: classpath:/static/
    view-names: index

  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
         max-age: 365d
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /api/swagger
  writer-with-default-pretty-printer: true
